import Head from 'next/head'
import styles from '@/styles/Contact.module.css'
import { withLayout } from '@/layout/Layout'

function Hobby(): JSX.Element {
  return (
    <>
      <Head key='head-hobby'>
        <title>Vasilika Klimova - Hobby</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <section>
        <p>I like:</p>
        <ul className={styles.hobbyList}>
          <li>🌍 traveling (I have visited more than 30 countries, and I want more!)</li>
          <li>🐍 animals (❤️ my ginger cat 😺)</li>
          <li>🤿 diving (rescue diver license)</li>
          <li>📚 reading (programming, psychology, fantasy)</li>
          <li>🎮 board games & video games (Mass Effect & Detroit: Become Human are my favourite)</li>
          <li>🎥 cinephile (based on true stories, science fiction, fantasy, romantic comedy)</li>
        </ul>
      </section>
    </>
  )
}

export default withLayout(Hobby)
