import Head from 'next/head'
// import styles from '@/styles/Contact.module.css'

export default function Projects() {
  return (
    <>
      <Head key='head-projects'>
        <title>Vasilika Klimova - Projects</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <>
        <h1>Projects</h1>
        <section></section>
      </>
    </>
  )
}
