import Head from 'next/head'
import styles from '@/styles/Speaker.module.css'
import events from './speaker.json'
import { withLayout } from '@/layout/Layout'
import { sortEvents } from '@/helpers/sortEvents'

function Speaker(): JSX.Element {
  const speaker = sortEvents(events.speaker)
  const articles = sortEvents(events.articles)
  const interview = sortEvents(events.podcasts)

  return (
    <>
      <Head key='head-speaker'>
        <title>Vasilika - Speaker</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <>
        <section>
          <h2>Speaker</h2>
          <p>I was a speaker at various meetups and conferences (50+):</p>
          <ul className={styles.eventList}>
            {speaker.map((event, index) => (
              <li key={`speaker-${index}`}>
                {
                  event.url ? <a href={event.url} rel='noopener nofollow' className={styles.underlineA} target='_blank'>
                    <strong>{event.name}</strong>
                  </a> : <span><strong>{event.name}</strong></span>
                }
                <br/>
                <span>{event.author}</span>, <span>{event.date}</span>
                <br/>
                {event.slides && (
                  <a href={event.slides} rel='noopener nofollow' target='_blank' className={styles.extraA}>
                    Slides
                  </a>
                )}
              </li>
            ))}
          </ul>
        </section>
        <section>
          <h2>Articles</h2>
          <ul className={styles.eventList}>
            {articles.map((event, index) => (
              <li key={`article-${index}`}>
                <a href={event.url} rel='noopener nofollow' className={styles.underlineA} target='_blank'>
                  <strong>{event.name}</strong>
                </a>
                <br />
                <span>{event.place}</span>, <span>{event.date}</span>
              </li>
            ))}
          </ul>
        </section>
        <section>
          <h2>Podcasts</h2>
          <ul className={styles.eventList}>
            {interview.map((event, index) => (
              <li key={`interview-${index}`}>
                <a href={event.url} rel='noopener nofollow' className={styles.underlineA} target='_blank'>
                  <strong>{event.name}</strong>
                </a>
                <br />
                <span>{event.author}</span>, <span>{event.date}</span>
              </li>
            ))}
          </ul>
        </section>
        <section>
          <h2>Communities</h2>
          <ul className={styles.eventList}>
            {events.community.map((event, index) => (
              <li key={`community-${index}`}>
                <a href={event.url} rel='noopener nofollow' className={styles.underlineA} target='_blank'>
                  <strong>{event.name}</strong>
                </a>
                , <span>{event.date}</span> - <span>{event.role}</span>
              </li>
            ))}
          </ul>
        </section>
        <section>
          <h2>Teacher</h2>
          <p>Since 2015 I have started to share my knowledge with others at different schools:</p>
          <ul className={styles.eventList}>
            {events.teacher.map((event, index) => (
              <li key={`teacher-${index}`}>
                <strong>{event.name}</strong>, {event.place}, {event.date} - <span>{event.position}</span>
              </li>
            ))}
          </ul>
        </section>
      </>
    </>
  )
}

export default withLayout(Speaker)
